const ACTIONS = Object.freeze({
    KILL: "KILL",
    SAVE: "SAVE",
    CHECK_ROLE: "CHECK_ROLE",
    BLOCK: "BLOCK",
    STEAL_VOTE: "STEAL_VOTE",
    DOUBLE_VOTE: "DOUBLE_VOTE",
    CANCEL_LYNCH: "CANCEL_LYNCH",
    COPY_ROLE: "COPY_ROLE",
    TAKE_ROLE_ONE_NIGHT: "TAKE_ROLE_ONE_NIGHT",
    LINK_PLAYERS: "LINK_PLAYERS",
    REFLECT: "REFLECT",
    REVENGE_KILL: "REVENGE_KILL",
    RANDOM_ROLE: "RANDOM_ROLE",
    TRANSFORM_ON_DEATH: "TRANSFORM_ON_DEATH",
});

module.exports = ACTIONS